*** Settings ***
Documentation    📚 Global settings and imports for all Robot Framework Test Suites

# Import all required resources
Resource         variables.resource
Resource         tests/test3/network_keywords.resource
Resource         tests/test4/vm_keywords.resource
Resource         tests/test6/os_keywords.resource
Resource         tests/test7/time_keywords.resource
Resource         tests/test8/security_keywords.resource